In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Data.csv")
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [5]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [6]:
pf=PolynomialFeatures(degree=3)
X_poly=pf.fit_transform(X_train)
print(X_train)

[[  15.83   41.67 1013.39   74.12]
 [  22.56   62.26 1012.11   63.16]
 [  22.11   59.8  1016.86   70.14]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [7]:
print(Y_train)

[464.93 445.33 450.62 ... 459.01 462.72 428.12]


In [8]:
lr=LinearRegression()

In [9]:
lr.fit(X_poly,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
Y_pred=lr.predict(pf.fit_transform(X_test))

In [11]:
from sklearn.metrics import r2_score

In [12]:
print(r2_score(Y_test,Y_pred))

0.9427897433267399
